// Generated by signage/tools/export_slide_data.py. Do not edit;
// every value here came from a run of the reference model or from
// a recorded experiment. Change the source and re-run the tool.
window.COCO_SIGNAGE = {
 "live": {
  "corpus": [
   "ACORN ARCHIMEDES",
   "ACORN BBC MICRO",
   "APPLE II",
   "APPLE LISA",
   "APPLE MACINTOSH",
   "ATARI 400",
   "ATARI 800",
   "ATARI ST",
   "COMMODORE 64",
   "COMMODORE 128",
   "COMMODORE AMIGA",
   "COMMODORE PET",
   "SINCLAIR ZX80",
   "SINCLAIR ZX81",
   "SINCLAIR ZX SPECTRUM",
   "TANDY COLOR COMPUTER",
   "TANDY TRS-80",
   "TANDY MODEL 100"
  ],
  "corpus_count": 18,
  "vocabulary": [
   "<END>",
   "100",
   "128",
   "400",
   "64",
   "800",
   "ACORN",
   "AMIGA",
   "APPLE",
   "ARCHIMEDES",
   "ATARI",
   "BBC",
   "COLOR",
   "COMMODORE",
   "COMPUTER",
   "II",
   "LISA",
   "MACINTOSH",
   "MICRO",
   "MODEL",
   "PET",
   "SINCLAIR",
   "SPECTRUM",
   "ST",
   "TANDY",
   "TRS-80",
   "ZX",
   "ZX80",
   "ZX81"
  ],
  "vocab_count": 29,
  "parameters": 290,
  "weight_bytes": 580,
  "program_bytes": 3338,
  "examples": 58,
  "epochs": 20,
  "corrections": 1160,
  "seed": 6809,
  "before": "800 100 COMMODORE MODEL SPECTRUM ZX81",
  "after": [
   {
    "text": "COMMODORE 128",
    "copied": true
   },
   {
    "text": "TANDY COMPUTER",
    "copied": false
   },
   {
    "text": "COMMODORE AMIGA",
    "copied": true
   },
   {
    "text": "TANDY ZX80",
    "copied": false
   },
   {
    "text": "COMMODORE ST",
    "copied": false
   },
   {
    "text": "TANDY PET",
    "copied": false
   },
   {
    "text": "COMMODORE LISA",
    "copied": false
   },
   {
    "text": "TANDY 128",
    "copied": false
   },
   {
    "text": "800 64",
    "copied": false
   },
   {
    "text": "TANDY APPLE 100 400 ZX ATARI",
    "copied": false
   },
   {
    "text": "ACORN BBC ZX TANDY",
    "copied": false
   }
  ],
  "copied_count": 2,
  "novel_count": 9,
  "checksum": "5ee491db953d0ce7"
 },
 "fans": {
  "columns": [
   {
    "label": "APPLE FAN",
    "samples": [
     "APPLE BBC",
     "APPLE MACINTOSH",
     "APPLE MACINTOSH",
     "APPLE 400"
    ],
    "epochs": 30
   },
   {
    "label": "COMMODORE FAN",
    "samples": [
     "COMMODORE 64",
     "COMMODORE AMIGA",
     "COMMODORE PET",
     "COMMODORE 64"
    ],
    "epochs": 30
   },
   {
    "label": "TANDY FAN",
    "samples": [
     "TANDY 1000",
     "TANDY COCO",
     "TANDY TRS-80",
     "TANDY 1000"
    ],
    "epochs": 30
   }
  ],
  "seeds": [
   6809,
   6810,
   6812,
   6816
  ]
 },
 "prompts": {
  "vocabulary": 38,
  "examples": 53,
  "completions": [
   {
    "prompt": "I ADORE",
    "completion": "MY 64",
    "verbatim": true
   },
   {
    "prompt": "ARE YOU",
    "completion": "KEEPING UP IN LITTLE COMPUTERS",
    "verbatim": false
   },
   {
    "prompt": "WHY BUY",
    "completion": "JUST A VIDEO GAME",
    "verbatim": true
   },
   {
    "prompt": "POWER WITHOUT",
    "completion": "THE PRICE",
    "verbatim": true
   }
  ],
  "copied_count": 3,
  "novel_count": 1
 },
 "titles": {
  "dealt": [
   "JOURNEY IN THE CAGE",
   "PLATO'S STEPCHILDREN TO TERROR",
   "METAMORPHOSIS OF GAMESTERS",
   "ERRAND TO CLOUD MINDERS",
   "YESTERDAYS ON THE TASTE",
   "PLATO'S STEPCHILDREN TO MERCY",
   "METHUSELAH FOR ZETAR",
   "SHORE LEAVE OF LIGHTS",
   "ELAAN OF ARCHONS",
   "PLATO'S STEPCHILDREN TO ELAAN",
   "BALANCE TO MUDD",
   "BALANCE OF BABEL",
   "ARENA OF METHUSELAH",
   "PARADISE OF SPOCK'S BRAIN",
   "GIDEON TO TRUTH",
   "PLATO'S STEPCHILDREN TO MIRI"
  ],
  "program_bytes": 4013,
  "real_titles": 79
 },
 "game": {
  "score_percent": 52.8,
  "rounds": 200
 },
 "context": {
  "model": "751B",
  "before": "CODE 2",
  "after": "CODE 6"
 },
 "bench": {
  "measured_on": "5 September 2026",
  "multiplications": 58000,
  "rows": [
   {
    "ticks": 519,
    "what": "6809 code, run as a 6809"
   },
   {
    "ticks": 442,
    "what": "same code, 6309 native mode"
   },
   {
    "ticks": 338,
    "what": "the 6309's MULD instruction"
   },
   {
    "ticks": 168,
    "what": "MULD at double clock"
   }
  ]
 }
};
