#!/usr/bin/env python3
"""Export real trained parameters for the 6309 multiply benchmark.

The benchmark is a standalone story, but it must not be a synthetic one. The
multiplicands are the numbers the model actually holds after twenty epochs,
and the 8-bit values are the context bytes a real forward pass feeds into the
multiply. A benchmark over invented data would measure the same instructions
and teach nothing about this workload.

The expected checksum is computed here, from the same wraparound arithmetic
the 6809 performs, so the assembly can assert it at build time. Both kernels
must reach it. A fast kernel with a different sum is a broken kernel.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from fixed_token_lm import FixedTokenLanguageModel  # noqa: E402
from token_lm import (  # noqa: E402
    ModelConfig,
    build_vocabulary,
    load_names,
    make_examples,
)

CORPUS = ROOT / "experiments" / "data" / "EXP-002-tokenized-computer-names.txt"
OUT = ROOT / "build" / "bench6309" / "bench_data.inc"
EPOCHS = 20


def signed8(value: int) -> int:
    value &= 0xFF
    return value - 256 if value & 0x80 else value


def main() -> None:
    names = load_names(CORPUS)
    vocabulary, by_text = build_vocabulary(names)
    config = ModelConfig()
    contexts, targets = make_examples(names, by_text, config.context)

    model = FixedTokenLanguageModel(config, vocabulary)
    model.train(contexts, targets, epochs=EPOCHS)

    weights = [int(v) for block in model.parameters for v in np.ravel(block)]

    # The 8-bit multiplicands the kernel really sees: the forward pass consumes
    # the context vector's high bytes as Q4.4.
    seen: list[int] = []
    for context in contexts:
        vector, _ = model._forward(np.asarray(context))
        seen.extend(signed8(int(v) >> 8) for v in vector)

    # One context byte per weight, so both pointers reset together and the
    # inner loop stays about the multiply rather than about addressing.
    multiplicands = [seen[i % len(seen)] for i in range(len(weights))]

    total = 0
    for a, w in zip(multiplicands, weights, strict=True):
        total = (total + a * w) & 0xFFFF

    lines = [
        "; Generated by tools/export_bench_data.py. Do not edit.",
        ";",
        f"; {len(weights)} parameters after {EPOCHS} epochs, and the context",
        "; bytes a real forward pass produces. BENCH_PASS_SUM is one pass of",
        "; the benchmark loop, computed in Python with the same 16-bit",
        "; wraparound the 6809 performs.",
        "",
        f"BENCH_COUNT     equ     {len(weights)}",
        f"BENCH_PASS_SUM  equ     ${total:04x}",
        "",
        "bench_weights",
    ]
    for i in range(0, len(weights), 8):
        row = ",".join(f"${w & 0xFFFF:04x}" for w in weights[i:i + 8])
        lines.append(f"        fdb     {row}")
    lines += ["", "bench_multiplicands"]
    for i in range(0, len(multiplicands), 12):
        row = ",".join(f"${a & 0xFF:02x}" for a in multiplicands[i:i + 12])
        lines.append(f"        fcb     {row}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))

    print(f"{len(weights)} parameters, {len(multiplicands)} multiplicands")
    print(f"one pass sums to ${total:04x}")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
