#!/usr/bin/env python3
"""Export the quantized melody model as 6809 assembly data.

Trains on the dance corpus, quantizes to signed bytes with both hardware
bounds proven unreachable, and writes the tables the CoCo will read: one
embedding table per context position, the output weights, and the biases.

Also writes a JSON manifest of the same numbers, so the parity test can check
the assembly against the reference without re-training.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from melody_fixed import SAMPLE_SHIFT, FixedMelodyModel
from melody_lm import ALL_FEATURES, MelodyConfig, MelodyModel, build_examples
from melody_tokens import MELODY_TOKENS, Tune

CORPUS = ROOT / "experiments" / "data" / "EXP-010-dance.jsonl"
OUTPUT_DIR = ROOT / "build" / "exp010"


def load(path: Path) -> list[Tune]:
    tunes = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        payload = json.loads(line)
        if payload["split"] == "train":
            tunes.append(Tune.from_json(payload))
    return tunes


def as_bytes(values) -> list[int]:
    """Signed values to the byte the 6809 will actually hold."""
    return [int(value) & 0xFF for value in values]


def emit_block(label: str, values: list[int], comment: str) -> list[str]:
    lines = [f"; {comment}", label]
    for start in range(0, len(values), 16):
        chunk = values[start : start + 16]
        lines.append("        fcb     " + ",".join(f"${b:02X}" for b in chunk))
    return lines


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=CORPUS)
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--history", type=int, default=12)
    parser.add_argument("--embedding", type=int, default=6)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    train = load(arguments.corpus)
    config = MelodyConfig(
        history=arguments.history,
        embedding=arguments.embedding,
        features=ALL_FEATURES,
    )
    contexts, targets = build_examples(train, config)
    model = MelodyModel(config)
    model.train(contexts, targets, epochs=arguments.epochs)
    fixed = FixedMelodyModel(model, contexts)
    report = fixed.report(contexts, targets)

    if not report.context_fits_byte:
        raise SystemExit(f"context bound {report.reachable_context} exceeds a byte")
    if not report.score_fits_accumulator:
        raise SystemExit(
            f"score bound {report.reachable_score} exceeds the accumulator"
        )

    lines = [
        "; Generated by tools/export_melody_model.py. Do not edit.",
        f"; {len(train)} training tunes, {config.parameters} parameters",
        (
            f"; reachable context {report.reachable_context}/127, "
            f"reachable score {report.reachable_score}/32767"
        ),
        "",
        f"MEL_TOKENS      equ     {MELODY_TOKENS}",
        f"MEL_EMBED       equ     {config.embedding}",
        f"MEL_CONTEXT     equ     {config.context}",
        f"MEL_HISTORY     equ     {config.history}",
        "",
        "; One table per context position, each rows x embedding signed bytes.",
        "; Positions run mode, metre, chord, beat, then melody history.",
        "mel_position_sizes",
        "        fcb     " + ",".join(str(n) for n in config.position_sizes),
        "",
        "mel_position_table",
        "        fdb     " + ",".join(f"mel_embed_{i}" for i in range(config.context)),
        "",
    ]

    total = 0
    for index, table in enumerate(fixed.embeddings):
        values = as_bytes(table.reshape(-1))
        total += len(values)
        lines += emit_block(
            f"mel_embed_{index}",
            values,
            f"position {index}: {table.shape[0]} rows x {table.shape[1]}",
        )
        lines.append("")

    weights = as_bytes(fixed.weights.reshape(-1))
    total += len(weights)
    lines += emit_block(
        "mel_weights", weights, f"output weights, {MELODY_TOKENS} x {config.embedding}"
    )
    lines.append("")

    lines += [
        "; exp(-d/32) as a byte; the tail reaches zero, which is deliberate",
        "mel_exp_lut",
    ]
    from melody_fixed import EXP_LUT

    for start in range(0, len(EXP_LUT), 16):
        chunk = EXP_LUT[start : start + 16]
        lines.append("        fcb     " + ",".join(f"${v:02X}" for v in chunk))
    lines += ["", f"MEL_SHIFT       equ     {SAMPLE_SHIFT}", ""]

    lines += ["; output biases, signed 16-bit at the score scale", "mel_biases"]
    for start in range(0, len(fixed.biases), 8):
        chunk = fixed.biases[start : start + 8]
        lines.append(
            "        fdb     " + ",".join(f"${int(v) & 0xFFFF:04X}" for v in chunk)
        )
    lines.append("")

    arguments.output_dir.mkdir(parents=True, exist_ok=True)
    inc = arguments.output_dir / "melody_model.inc"
    inc.write_text("\n".join(lines), encoding="ascii")

    manifest = {
        "history": config.history,
        "embedding": config.embedding,
        "context": config.context,
        "features": list(config.features),
        "position_sizes": list(config.position_sizes),
        "melody_tokens": MELODY_TOKENS,
        "embedding_scale": fixed.embedding_scale,
        "weight_scale": fixed.weight_scale,
        "product_scale": fixed.product_scale,
        "reachable_context": report.reachable_context,
        "reachable_score": report.reachable_score,
        "sample_shift": SAMPLE_SHIFT,
        "bits": report.bits,
        "embeddings": [table.tolist() for table in fixed.embeddings],
        "weights": fixed.weights.tolist(),
        "biases": fixed.biases.tolist(),
    }
    (arguments.output_dir / "melody_model.json").write_text(
        json.dumps(manifest), encoding="ascii"
    )

    print(f"training tunes: {len(train)}   parameters: {config.parameters}")
    print(f"context positions: {config.context} (4 situational + {config.history})")
    print(f"weight bytes: {total}   bias words: {len(fixed.biases)}")
    print(f"total image: {total + 2 * len(fixed.biases)} bytes")
    print(f"reachable context {report.reachable_context}/127")
    print(f"reachable score   {report.reachable_score}/32767")
    print(f"holdout-free training bits {report.bits:.3f}")
    print(f"\nwrote {inc}")
    print(f"wrote {arguments.output_dir / 'melody_model.json'}")


if __name__ == "__main__":
    main()
