#!/usr/bin/env python3
"""Compile the demo tune into the event stream the EXP-018 player replays.

The sample rate is the loop's exact cycle count, with nothing amortised,
because every sample of this player costs the same. Pass the rate the
cycle model gives and every note is in tune and every tick is on time.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from coco_synth import demo_tune, steady_tune  # noqa: E402
from steady_synth import PAGE, SCRATCH, compile_events, stream_bytes  # noqa: E402


def render_source(tune, *, sample_rate: int, repeats: int) -> str:
    events = compile_events(tune, sample_rate)
    data = stream_bytes(events)
    fillers = sum(1 for event in events if event.address == PAGE + SCRATCH)
    lines = [
        "; Generated by tools/export_events.py. Do not edit.",
        f"; tune: {tune.name}",
        f"; sample rate: {sample_rate} Hz, {round(sample_rate / tune.tick_hz)} "
        f"samples per tick",
        f"; {len(events)} events, {fillers} of them fillers that split a long wait",
        "",
        f"TUNE_REPEATS    equ {repeats}",
        f"EVENT_BYTES     equ {len(data)}",
        "",
        "; wait, address, value, wait, address, value, ... and one spare byte.",
        "event_stream",
    ]
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        lines.append("        fcb     " + ",".join(f"${byte:02X}" for byte in chunk))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--sample-rate", type=int, required=True)
    parser.add_argument("--repeats", type=int, default=2)
    parser.add_argument("--tune", choices=("demo", "steady"), default="demo")
    arguments = parser.parse_args()
    tune = steady_tune() if arguments.tune == "steady" else demo_tune()
    source = render_source(
        tune, sample_rate=arguments.sample_rate, repeats=arguments.repeats
    )
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(source, encoding="ascii")
    events = compile_events(tune, arguments.sample_rate)
    print(f"tune: {tune.name}   events: {len(events)}   bytes: {len(events) * 4 + 1}")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    main()
