#!/usr/bin/env python3
"""Export the demo tune and note-increment table as 6809 assembly data.

The increment table is the only place the sample rate appears in the player.
Because the 6809's real sample rate is whatever its inner loop costs, the rate
is a parameter here: measure the loop, pass the measured rate, and every note
is in tune.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from coco_synth import (
    MAX_VOLUME,
    NOTE_HOLD,
    NOTE_OFF,
    VOICE_COUNT,
    Tune,
    demo_tune,
    note_increment,
)

DEFAULT_OUTPUT = ROOT / "build" / "exp009" / "tune_data.inc"
LOW_NOTE = 12
HIGH_NOTE = 108

NOTE_HOLD_CODE = 0
NOTE_OFF_CODE = 1


def encode_cell(cell) -> tuple[int, int, int]:
    """Encode one cell as note, volume+flags, decay."""
    if cell.note == NOTE_HOLD:
        return (NOTE_HOLD_CODE, 0, 0)
    if cell.note == NOTE_OFF:
        return (NOTE_OFF_CODE, 0, 0)

    if not LOW_NOTE <= cell.note <= HIGH_NOTE:
        raise ValueError(f"note {cell.note} is outside {LOW_NOTE}..{HIGH_NOTE}")
    if cell.note in (NOTE_HOLD_CODE, NOTE_OFF_CODE):
        raise ValueError(f"note {cell.note} collides with a control code")

    flags = min(MAX_VOLUME, cell.volume) | (0x80 if cell.noise else 0x00)
    return (cell.note, flags, min(255, cell.decay))


def render_source(tune: Tune, *, sample_rate: int, repeats: int) -> str:
    samples_per_tick = round(sample_rate / tune.tick_hz)
    if not 1 <= samples_per_tick <= 255:
        raise ValueError(f"samples per tick {samples_per_tick} does not fit a byte")
    if not 1 <= len(tune.rows) <= 255:
        raise ValueError(f"row count {len(tune.rows)} does not fit a byte")

    lines = [
        "; Generated by tools/export_tune.py. Do not edit.",
        f"; tune: {tune.name}",
        f"; sample rate: {sample_rate} Hz, tick rate: {tune.tick_hz} Hz",
        "",
        f"SAMPLES_PER_TICK equ {samples_per_tick}",
        f"TICKS_PER_ROW   equ {tune.ticks_per_row}",
        f"TUNE_ROWS       equ {len(tune.rows)}",
        f"TUNE_REPEATS    equ {repeats}",
        "",
        (
            f"; Phase increments for MIDI notes {LOW_NOTE}..{HIGH_NOTE} "
            f"at {sample_rate} Hz."
        ),
        "note_increments",
    ]

    for note in range(LOW_NOTE, HIGH_NOTE + 1):
        increment = note_increment(note, sample_rate)
        lines.append(f"        fdb     ${increment:04X}    ; note {note}")

    lines += ["", "; Rows of four cells: note, volume+flags, decay.", "tune_rows"]
    for number, row in enumerate(tune.rows):
        if len(row) != VOICE_COUNT:
            raise ValueError(f"row {number} has {len(row)} cells")
        encoded = [value for cell in row for value in encode_cell(cell)]
        body = ",".join(f"${value:02X}" for value in encoded)
        lines.append(f"        fcb     {body}    ; row {number}")

    lines.append("")
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--sample-rate", type=int, default=7300)
    parser.add_argument("--repeats", type=int, default=2)
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    tune = demo_tune()
    source = render_source(
        tune, sample_rate=arguments.sample_rate, repeats=arguments.repeats
    )
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(source, encoding="ascii")

    print(f"tune: {tune.name}")
    print(f"rows: {len(tune.rows)}   bytes of row data: {len(tune.rows) * 12}")
    print(f"increment table: {(HIGH_NOTE - LOW_NOTE + 1) * 2} bytes")
    print(f"samples per tick: {round(arguments.sample_rate / tune.tick_hz)}")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    main()
