#!/usr/bin/env python3
"""Train and export the EXP-006 inference-only CoCo model image."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from completion_lm import (
    AdditiveCompletionModel,
    NeuralConfig,
    build_completion_vocabulary,
    largest_additive_embedding,
    load_phrases,
    make_completion_examples,
    suggest,
    train_neural_model,
)

DEFAULT_TRAINING = ROOT / "experiments" / "data" / "EXP-006-completion-training.txt"


def decb_binary(payload: bytes, *, load_address: int) -> bytes:
    if not 0 <= load_address <= 0xFFFF:
        raise ValueError("load address must be a 16-bit value")
    if len(payload) > 0xFFFF:
        raise ValueError("DECB block cannot exceed 65,535 bytes")
    return b"".join(
        (
            b"\x00",
            len(payload).to_bytes(2, "big"),
            load_address.to_bytes(2, "big"),
            payload,
            b"\xff\x00\x00\x00\x00",
        )
    )


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--training", type=Path, default=DEFAULT_TRAINING)
    parser.add_argument(
        "--output-directory",
        type=Path,
        default=ROOT / "build" / "exp006",
    )
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument(
        "--load-address", type=lambda text: int(text, 0), default=0x6000
    )
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    phrases = load_phrases(arguments.training)
    vocabulary, token_by_text = build_completion_vocabulary(phrases)
    contexts, targets = make_completion_examples(phrases, token_by_text, 4)
    embedding = largest_additive_embedding(len(vocabulary), 4, 8192)
    model = AdditiveCompletionModel(
        NeuralConfig(context=4, embedding=embedding),
        vocabulary,
    )
    losses = train_neural_model(
        model,
        contexts,
        targets,
        epochs=arguments.epochs,
        learning_rate=0.01,
        batch_size=32,
    )
    fixed = model.int8_copy()
    image = fixed.model_bytes(padded_size=8192)
    context_vectors = [fixed.context_vector(context) for context in contexts]
    maximum_context_magnitude = max(
        abs(int(value)) for vector in context_vectors for value in vector
    )
    if maximum_context_magnitude > 127:
        raise ValueError("observed context vector does not fit signed 8-bit")
    all_context_minimum = np.min(
        fixed.position_embeddings.astype(np.int64), axis=1
    ).sum(axis=0)
    all_context_maximum = np.max(
        fixed.position_embeddings.astype(np.int64), axis=1
    ).sum(axis=0)
    all_context_magnitude = int(
        max(
            np.max(np.abs(all_context_minimum)),
            np.max(np.abs(all_context_maximum)),
        )
    )
    if all_context_magnitude > 127:
        raise ValueError("some possible context vector does not fit signed 8-bit")

    output = arguments.output_directory
    output.mkdir(parents=True, exist_ok=True)
    (output / "weights.bin").write_bytes(image)
    (output / "weights.decb").write_bytes(
        decb_binary(image, load_address=arguments.load_address)
    )
    (output / "vocabulary.txt").write_text(
        "\n".join(vocabulary) + "\n", encoding="ascii"
    )

    prompts = [
        ["PRESS", "TAB", "TO"],
        ["LOAD", "THE"],
        ["THE", "COMMODORE"],
        ["THE", "MODEL", "PREDICTS"],
        ["HUMANS", "CHECK", "THE"],
    ]
    tests = []
    boundary = token_by_text["<END>"]
    for words in prompts:
        context = [boundary] * 4
        for word in words[-4:]:
            context = context[1:] + [token_by_text[word]]
        integer_scores = fixed.integer_scores(context_array(context))
        ranking = sorted(
            range(len(vocabulary)),
            key=lambda index: (-int(integer_scores[index]), index),
        )
        ranking = [index for index in ranking if index != boundary][:3]
        tests.append(
            {
                "prompt": " ".join(words),
                "context_tokens": context,
                "context_vector": [
                    int(value) for value in fixed.context_vector(context_array(context))
                ],
                "top_three_tokens": ranking,
                "top_three_words": [vocabulary[index] for index in ranking],
                "top_three_scores": [int(integer_scores[index]) for index in ranking],
            }
        )
    (output / "test-vectors.json").write_text(
        json.dumps(tests, indent=2) + "\n", encoding="ascii"
    )
    first_test = tests[0]
    assembly = [
        "; Generated by tools/export_exp_006.py. Do not edit.",
        f"EXP6_VOCAB_SIZE        equ     {len(vocabulary)}",
        "EXP6_CONTEXT_SIZE      equ     4",
        f"EXP6_EMBED_DIMS        equ     {embedding}",
        f"EXP6_PARAM_COUNT       equ     {fixed.parameter_count}",
        f"EXP6_MODEL_BASE        equ     ${arguments.load_address:04x}",
        (
            "EXP6_OUTPUT_WEIGHTS    equ     "
            f"EXP6_MODEL_BASE+{fixed.position_embeddings.size}"
        ),
        (
            "EXP6_OUTPUT_BIASES     equ     "
            f"EXP6_OUTPUT_WEIGHTS+{fixed.output_weights.size}"
        ),
        "",
        "exp6_test_context",
        "        fcb     "
        + ",".join(f"${token:02x}" for token in first_test["context_tokens"]),
        "exp6_expected_top_three",
        "        fcb     "
        + ",".join(f"${token:02x}" for token in first_test["top_three_tokens"]),
        "",
    ]
    (output / "model_data.inc").write_text("\n".join(assembly), encoding="ascii")

    offsets = {
        "position_embeddings": 0,
        "output_weights": fixed.position_embeddings.size,
        "output_biases": (fixed.position_embeddings.size + fixed.output_weights.size),
        "padding": fixed.parameter_count,
    }
    manifest = {
        "experiment": 6,
        "format": "signed Q4.4 bytes",
        "layout": offsets,
        "load_address": arguments.load_address,
        "context": 4,
        "embedding": embedding,
        "vocabulary_size": len(vocabulary),
        "parameters": fixed.parameter_count,
        "image_bytes": len(image),
        "padding_bytes": len(image) - fixed.parameter_count,
        "inference_multiplies": fixed.inference_multiplies,
        "observed_maximum_context_magnitude": maximum_context_magnitude,
        "all_possible_maximum_context_magnitude": all_context_magnitude,
        "epochs": arguments.epochs,
        "initial_epoch_loss": losses[0],
        "final_epoch_loss": losses[-1],
        "sha256": hashlib.sha256(image).hexdigest(),
        "sample_suggestions": {
            " ".join(prompt): suggest(fixed, prompt) for prompt in prompts
        },
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
    )
    print(f"wrote {len(image)} bytes to {output / 'weights.bin'}")
    print(f"SHA-256: {manifest['sha256']}")
    print(
        f"{len(vocabulary)} tokens, {fixed.parameter_count} parameters, "
        f"{fixed.inference_multiplies} multiplies/suggestion"
    )


def context_array(values: list[int]):
    return np.asarray(values, dtype=np.int64)


if __name__ == "__main__":
    main()
