#!/usr/bin/env python3
"""Export a wavetable as 6809 assembly data for the EXP-017 player.

Sixteen pages of 256 bytes, one page per volume, in the DAC's PA2-PA7
units (the reference's 0-15 values times four). The table starts on a
256-byte boundary so that a voice's page number and its phase high byte,
read as one 16-bit word, are the address of its next sample.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from wave_synth import PAGE_SAMPLES, PAGES, SHAPES, wave_table


def render_source(shape: str) -> str:
    table = wave_table(shape)
    lines = [
        "; Generated by tools/export_wavetable.py. Do not edit.",
        f"; shape: {shape}. {PAGES} volume pages of {PAGE_SAMPLES} samples,",
        "; in PA2-PA7 units. Page n is volume n.",
        "",
        "                org     (*+255)&$FF00   ; next 256-byte boundary",
        "wave_table",
    ]
    for volume, page in enumerate(table):
        lines.append(f"; volume {volume}")
        for start in range(0, PAGE_SAMPLES, 16):
            chunk = page[start : start + 16]
            lines.append(
                "        fcb     " + ",".join(f"${value * 4:02X}" for value in chunk)
            )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shape", choices=tuple(SHAPES), default="triangle")
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render_source(arguments.shape), encoding="ascii")
    print(f"shape: {arguments.shape}   {PAGES * PAGE_SAMPLES} bytes")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    main()
