"""Generate deterministic 6809 assembly data from the reference model."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src" / "reference"))

from fixed_token_lm import EXP_LUT, FixedTokenLanguageModel
from token_lm import ModelConfig, build_vocabulary, load_names, make_examples


def assembly_bytes(values: list[int], *, width: int = 12) -> list[str]:
    return [
        "        fcb     "
        + ",".join(f"${value & 0xFF:02x}" for value in values[offset : offset + width])
        for offset in range(0, len(values), width)
    ]


def assembly_words(values: list[int], *, width: int = 8) -> list[str]:
    return [
        "        fdb     "
        + ",".join(
            f"${value & 0xFFFF:04x}" for value in values[offset : offset + width]
        )
        for offset in range(0, len(values), width)
    ]


def safe_label(token: str, index: int) -> str:
    translated = "".join(
        character if character.isalnum() else "_" for character in token
    )
    return f"token_{index:02d}_{translated}"


def generate(root: Path, epochs: int) -> str:
    corpus = root / "experiments" / "data" / "EXP-002-tokenized-computer-names.txt"
    names = load_names(corpus)
    vocabulary, token_by_text = build_vocabulary(names)
    contexts, targets = make_examples(names, token_by_text, context_size=2)

    model = FixedTokenLanguageModel(ModelConfig(seed=6809), vocabulary)
    model.train(contexts, targets, epochs=epochs)
    parameters = [
        int(value) for parameter in model.parameters for value in parameter.reshape(-1)
    ]

    lines = [
        "; Generated by tools/generate_6809_data.py. Do not edit.",
        f"VOCAB_SIZE      equ     {len(vocabulary)}",
        f"EXAMPLE_COUNT   equ     {len(targets)}",
        f"TRAIN_EPOCHS    equ     {epochs}",
        f"PARAM_COUNT     equ     {len(parameters)}",
        "",
        "training_examples",
    ]
    examples = [
        value
        for context, target in zip(contexts, targets, strict=True)
        for value in (*context.tolist(), int(target))
    ]
    lines.extend(assembly_bytes(examples))
    lines.extend(["", "exp_lut"])
    lines.extend(assembly_bytes([int(value) for value in EXP_LUT]))
    lines.extend(["", "token_pointers"])
    for index, token in enumerate(vocabulary):
        lines.append(f"        fdb     {safe_label(token, index)}")
    lines.append("")
    for index, token in enumerate(vocabulary):
        encoded = [ord(character) for character in token] + [0]
        lines.append(safe_label(token, index))
        lines.extend(assembly_bytes(encoded))
    lines.extend(["", "expected_parameters"])
    lines.extend(assembly_words(parameters))
    lines.extend(
        [
            "",
            f"; Reference SHA-256: {model.checksum()}",
            "expected_checksum_text",
            *assembly_bytes(
                [ord(character) for character in model.checksum()[:16]] + [0]
            ),
            "",
        ]
    )
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--epochs", type=int, default=20)
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generate(ROOT, arguments.epochs))


if __name__ == "__main__":
    main()
